config/routes.rb
Rails.application.routes.draw do

  root 'course#show'

  devise_for :users, controllers: { registrations: "custom/registrations" }
  devise_scope :user do
    get 'custom/registrations/custom_new', to: 'custom/registrations#custom_new', as: 'custom_new'
    post 'custom/registrations/custom_create', to: 'custom/registrations#custom_create', as: 'user_custom_create'
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_login
    post 'login' => 'devise/sessions#create', :as => :user_login
    get 'signup' => 'devise/registrations#new', :as => :user_signup
  end

  get 'sign_up_course' => 'course#sign_up_course'
  get '/course/:title/sign_in' => 'course#sign_in'

  resources :course

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	def index
		#load first 8 courses from course model
		@courses = Course.first(8)
		unless user_signed_in?  
			#	@usrname = current_user.name
		    redirect_to new_user_session_path
		end	
	end

	def test
		
	end

	def search
			
	end
end

app/helpers/home_helper.rb
module HomeHelper
	
end

app/views/home/index.html.erb
<div class="container caroushow">

	<ul>
		<% @courses.each do |course| %>
	  		<%= link_to course.title, course_path(course) %>
		<% end %>
	</ul>


	<div class="slogan">
		<h2> 口袋裡的健身教練與營養師 </h2>
	</div>
	<div class="search-box">
		<div class=""></div>
		<input type="text" placeholder="今天想從哪開始呢？"></input>
	</div>
	<div class="mask"></div>
	<div id="headCarousel" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner" role="listbox">
			<div class="picture_box item active">
				<%= image_tag("nav1-big.jpg") %>
			</div>
			<div class="item picture_box">
				<%= image_tag("nav2-big.jpg") %>
			</div>
			<div class="item picture_box">
				<%= image_tag("nav3-big.jpg") %>
			</div>
		</div>
	</div>
</div>
<div class="container">		
	<div class="subtitle">
		<h2>熱門課程</h2>
	</div>
	<div class="row block">
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("bike.jpg")
			%><span>臣亮言：先帝創業未半</span>
			<span class="teacher">諸葛孔明</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("yoga.jpg")
			%><span>而中道崩殂。今天下三分</span>
			<span class="teacher">蔡英文</span>	
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("bike.jpg")
			%><span>益州疲弊，此誠危急存亡之秋也</span>
			<span class="teacher">朱立倫</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness2.jpg") %>
			<span>然侍衛之臣，不懈於內</span>
			<span class="teacher">宋楚瑜</span>
		</div>
		<div class="clearfix col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness.jpg")
			%>			<span>忠志之士，忘身於外者</span>
			<span class="teacher">柯文哲</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("rock.jpg")
			%><span>蓋追先帝之殊遇，欲報之於陛下也</span>
			<span class="teacher">三姊弟布丁</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness3.png") %>
			<span>誠宜開張聖聽，以光先帝遺德</span>
			<span class="teacher">Henry Lin</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("ship.png")
			%><span>恢弘志士之氣；不宜妄自菲薄</span>
			<span class="teacher">陳菊</span>
		</div>
	</div>

</div>

<div class="container">		
	<div class="subtitle">
		<h1>即將開設課程</h1>
	</div>
	<div class="row block">
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("bike.jpg")
			%><span>臣亮言：先帝創業未半</span>
			<span class="teacher">諸葛孔明</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("yoga.jpg")
			%><span>而中道崩殂。今天下三分</span>
			<span class="teacher">蔡英文</span>	
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("bike.jpg")
			%><span>益州疲弊，此誠危急存亡之秋也</span>
			<span class="teacher">朱立倫</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness2.jpg") %>
			<span>然侍衛之臣，不懈於內</span>
			<span class="teacher">宋楚瑜</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness.jpg")
			%>			<span>忠志之士，忘身於外者</span>
			<span class="teacher">柯文哲</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("rock.jpg")
			%><span>蓋追先帝之殊遇，欲報之於陛下也</span>
			<span class="teacher">三姊弟布丁</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("fitness3.png") %>
			<span>誠宜開張聖聽，以光先帝遺德</span>
			<span class="teacher">Henry Lin</span>
		</div>
		<div class="col-xs-4 col-sm-4 col-md-3 black">
			<%= image_tag("ship.png") %>
			<span>恢弘志士之氣；不宜妄自菲薄</span>
			<span class="teacher">陳菊</span>
		</div>
	</div>

</div>