config/routes.rb
Rails.application.routes.draw do

  root 'course#show'

  devise_for :users, controllers: { registrations: "custom/registrations" }
  devise_scope :user do
    get 'custom/registrations/custom_new', to: 'custom/registrations#custom_new', as: 'custom_new'
    post 'custom/registrations/custom_create', to: 'custom/registrations#custom_create', as: 'user_custom_create'
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_login
    post 'login' => 'devise/sessions#create', :as => :user_login
    get 'signup' => 'devise/registrations#new', :as => :user_signup
  end

  get 'sign_up_course' => 'course#sign_up_course'
  get '/course/:title/sign_in' => 'course#sign_in'

  resources :course

end

app/views/layouts/_footer.html.erb
<% if not need_header? controller.controller_name %>
<footer class="copy_rights">
	<span> © 2016 Donchi Inc. All rights reserved. </span>
</footer>
<% end %>

app/views/layouts/_header.html.erb
<% if not need_header? controller.controller_name %>
<header>
	<div class="icon pull-left">
		<%= image_tag 'icon/white_word_aside.png' %>
	</div>
	<div class="login pull-right">
		<% unless user_signed_in? %>
			<%= link_to 'login', user_login_path%>
		<% else %>
			<%= link_to 'sign out', destroy_user_session_path, method: :delete %>
		<% end %>
	</div>

	<!-- <div class="popup">
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	</div> -->
</header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Donchi</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

</head>
<body>

	<%= render 'layouts/header' %>
	<%= yield %>

	<%= render 'layouts/footer' %>
	<!-- Inlcude HTML5 Shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

</body>
</html>